"""Derives the initial commit's files from a project's Spec Kit stage
documents (constitution/specify/plan/tasks) at the `tech_review ->
repo_created` transition (see app/api/sync.py's `create_repository`).

Pure and I/O-free on purpose: no network, no LLM call, no widening of the
`stage` Literal (closed in schemas.py, api/stage_documents.py, the Postgres
CHECK in migrations/0019_stage_documents.sql, and the web STAGE_ORDER). The
seeded files here are just derived *views* over those four documents plus a
project's Policy Scope (app/models/schemas.py::PolicyScope), composed at
commit time — not a new document kind.

Derived views, one SeedFile per non-empty input:
  AGENTS.md                          constitution (or a stub)
  README.md                          specify (or a stub)
  docs/scope.md                      specify
  docs/architecture.md               plan
  docs/tasks.md                      tasks
  docs/conventions.md                the constitution's "Conventions" section (or a stub)
  .specify/memory/constitution.md    the constitution verbatim — this is what makes the
                                      engine's own `withConstitution()` (apps/engine/src/
                                      routes/projects.ts) inherit policy for desktop/engine
                                      users, since that's the exact path it reads
  docs/policy-scope.md               the project's policy scope, full template bodies +
                                      custom text — only when a scope was selected
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from app.deployments.plan_profile import derive_stack_profile
from app.deployments.registry import get_template as get_deployment_template
from app.deployments.registry import (
    is_composed_scaffold,
    render_deployment_doc,
    template_files,
)
from app.models.schemas import Project
from app.policies.registry import render_policy_scope_doc

_PREAMBLE = (
    "<!-- Rules for AI coding agents here. Generated by PromptZone at repo "
    "creation; edit freely — never overwritten. -->\n\n"
)


@dataclass(frozen=True)
class SeedFile:
    path: str
    content: str
    # Git tree mode 100755 rather than 100644. Only deployment-template
    # scaffolds set this (a build script a workflow invokes); every derived
    # document below is a plain file.
    executable: bool = False


def _footer(project: Project) -> str:
    date = datetime.now(timezone.utc).date().isoformat()
    return f"\n\n<!-- Generated by PromptZone for project {project.id} on {date}. -->\n"


def _conventions_section(constitution: str | None) -> str | None:
    """Dumb heading scan: find a "Conventions" heading (any level) and return
    everything up to the next heading of the same or shallower level. No LLM
    call — a best-effort extraction, not a parse."""
    if not constitution:
        return None
    lines = constitution.splitlines()
    start = None
    start_level = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.lower().lstrip("#").strip() == "conventions" and stripped.startswith("#"):
            start = i
            start_level = len(stripped) - len(stripped.lstrip("#"))
            break
    if start is None:
        return None
    end = len(lines)
    for j in range(start + 1, len(lines)):
        stripped = lines[j].strip()
        if stripped.startswith("#"):
            level = len(stripped) - len(stripped.lstrip("#"))
            if level <= start_level:
                end = j
                break
    section = "\n".join(lines[start:end]).strip()
    return section or None


def build_seed_files(project: Project, stage_docs: dict[str, str | None]) -> list[SeedFile]:
    """`stage_docs` maps stage name ("constitution"/"specify"/"plan"/"tasks")
    to its content, or is missing/None/empty for a stage never generated.
    Missing/empty stage doc -> that file is skipped, except AGENTS.md and
    README.md, which always get a stub — repo creation must never fail on a
    partially-planned project."""
    constitution = (stage_docs.get("constitution") or "").strip() or None
    specify = (stage_docs.get("specify") or "").strip() or None
    plan = (stage_docs.get("plan") or "").strip() or None
    tasks = (stage_docs.get("tasks") or "").strip() or None

    files: list[SeedFile] = []

    agents_body = constitution or (
        "No constitution has been generated for this project yet. "
        "Add project-specific rules for AI coding agents here."
    )
    files.append(SeedFile("AGENTS.md", _PREAMBLE + agents_body + _footer(project)))

    readme_lines = [f"# {project.name}", ""]
    readme_lines.append(
        f"Managed by PromptZone. See the project in the cloud workspace: "
        f"project id `{project.id}`."
    )
    readme_lines.append("")
    if specify:
        readme_lines.append("## Scope")
        readme_lines.append("")
        readme_lines.append(specify)
    else:
        readme_lines.append("## Scope")
        readme_lines.append("")
        readme_lines.append("No scope/spec has been generated for this project yet.")
    files.append(SeedFile("README.md", "\n".join(readme_lines) + _footer(project)))

    if specify:
        files.append(SeedFile("docs/scope.md", specify + _footer(project)))

    if plan:
        files.append(SeedFile("docs/architecture.md", plan + _footer(project)))

    if tasks:
        files.append(SeedFile("docs/tasks.md", tasks + _footer(project)))

    conventions = _conventions_section(constitution)
    if conventions:
        files.append(SeedFile("docs/conventions.md", conventions + _footer(project)))
    else:
        files.append(
            SeedFile(
                "docs/conventions.md",
                "Conventions are documented in `AGENTS.md` at the repo root."
                + _footer(project),
            )
        )

    if constitution:
        # This is what lets the engine's own `withConstitution()` inherit
        # policy for desktop/engine users (see module docstring) — it reads
        # exactly this path and, before this feature, the cloud never seeded
        # it at all.
        files.append(
            SeedFile(".specify/memory/constitution.md", constitution + _footer(project))
        )

    scope = project.policy_scope
    if scope is not None and (scope.selected or scope.custom_text.strip()):
        files.append(
            SeedFile("docs/policy-scope.md", render_policy_scope_doc(scope) + _footer(project))
        )

    return files


def build_deployment_files(
    project: Project, preview_url: str | None, plan_text: str | None = None
) -> list[SeedFile]:
    """The deployment template's scaffold, workflow and `docs/deployment.md`
    (ADR 0021), or an empty list when no template was selected.

    `plan_text` is the project's `plan` stage document, and it only matters to
    a template with a composed scaffold (ADR 0026): the runtime and the
    backing services are read off it by a keyword scan, which then *selects*
    among hand-written files. Nothing here generates a file, so this function
    stays as pure and as deterministic as it was — the same plan text seeds
    the same tree.

    Kept separate from `build_seed_files` rather than folded into it, for two
    reasons. These files are *verbatim scaffold* rather than derived views
    over stage documents, so the module docstring's contract above still
    holds exactly. And a project with no template must produce a byte-identical
    seed to the one it produced before this feature existed — which is much
    easier to keep true, and to test, when the two builders cannot interact.

    Pure and I/O-free in the same sense as its sibling: template files are
    read from this package's own directory, the way
    app/policies/registry.py::template_body already reads policy bodies. No
    network, no model call.
    """
    config = project.deployment_config
    if config is None:
        return []
    template = get_deployment_template(config.template_id)
    if template is None:
        # A selection that no longer resolves (a template withdrawn between
        # selection and repo creation) seeds nothing rather than failing the
        # transition: the repo and its AI context are still worth having.
        return []

    profile = derive_stack_profile(plan_text)
    files = [
        SeedFile(path, content, executable=executable)
        for path, content, executable in template_files(template.id, profile)
    ]
    files.append(
        SeedFile(
            template.docs_path,
            render_deployment_doc(
                template,
                project_name=project.name,
                preview_url=preview_url,
                # Only a composed scaffold's document says what the plan
                # decided; for a flat template there is nothing to report and
                # the section would be noise.
                profile=profile if is_composed_scaffold(template.id) else None,
            )
            + _footer(project),
        )
    )
    return files
