"""app/integrations/repo_seed.py: pure, I/O-free derivation of the files
seeded into a project's repo at the tech_review -> repo_created transition.
"""

from __future__ import annotations

from app.deployments.registry import get_template, template_files
from app.integrations.deploy_providers import PROVIDERS
from app.integrations.repo_seed import build_deployment_files, build_seed_files
from app.models.schemas import DeploymentConfig, PolicyScope, Project


def _project(**overrides) -> Project:
    defaults = dict(name="Rocket", workspace_id="ws-1", owner_id="alice")
    defaults.update(overrides)
    return Project(**defaults)


def test_full_stage_docs_produce_all_files():
    project = _project()
    constitution = (
        "# Constitution\n\nSome rules.\n\n"
        "## Conventions\n\n- Use snake_case.\n- No TODOs.\n\n"
        "## Other\n\nMore stuff."
    )
    stage_docs = {
        "constitution": constitution,
        "specify": "# Scope\n\nBuild a rocket.",
        "plan": "# Architecture\n\nUse staged boosters.",
        "tasks": "# Tasks\n\nT001: build stage one.",
    }
    files = build_seed_files(project, stage_docs)
    paths = {f.path for f in files}
    assert paths == {
        "AGENTS.md",
        "README.md",
        "docs/scope.md",
        "docs/architecture.md",
        "docs/tasks.md",
        "docs/conventions.md",
        ".specify/memory/constitution.md",
    }

    by_path = {f.path: f.content for f in files}
    assert "Some rules." in by_path["AGENTS.md"]
    assert "Build a rocket." in by_path["README.md"]
    assert by_path["docs/scope.md"].startswith("# Scope")
    assert "Use staged boosters." in by_path["docs/architecture.md"]
    assert "T001" in by_path["docs/tasks.md"]
    assert "Use snake_case." in by_path["docs/conventions.md"]
    assert "Other" not in by_path["docs/conventions.md"]
    assert "Some rules." in by_path[".specify/memory/constitution.md"]


def test_no_constitution_doc_means_no_specify_memory_file():
    project = _project()
    files = build_seed_files(project, {"specify": "# Scope\n\nBuild a rocket."})
    paths = {f.path for f in files}
    assert ".specify/memory/constitution.md" not in paths


def test_policy_scope_seeds_docs_policy_scope_file():
    scope = PolicyScope(selected=["thai-pdpa"], custom_text="Be extra careful.")
    project = _project(policy_scope=scope)
    files = build_seed_files(project, {"constitution": "# Constitution\n\nRules."})
    by_path = {f.path: f.content for f in files}
    assert "docs/policy-scope.md" in by_path
    assert "Thai PDPA" in by_path["docs/policy-scope.md"]
    assert "Be extra careful." in by_path["docs/policy-scope.md"]


def test_custom_text_only_policy_scope_still_seeds_the_file():
    project = _project(policy_scope=PolicyScope(selected=[], custom_text="Only custom guidance."))
    files = build_seed_files(project, {})
    by_path = {f.path: f.content for f in files}
    assert "docs/policy-scope.md" in by_path
    assert "Only custom guidance." in by_path["docs/policy-scope.md"]


def test_no_policy_scope_means_no_policy_scope_file():
    project = _project()  # policy_scope defaults to None
    files = build_seed_files(project, {"constitution": "# Constitution\n\nRules."})
    paths = {f.path for f in files}
    assert "docs/policy-scope.md" not in paths


def test_empty_policy_scope_means_no_policy_scope_file():
    project = _project(policy_scope=PolicyScope(selected=[], custom_text=""))
    files = build_seed_files(project, {"constitution": "# Constitution\n\nRules."})
    paths = {f.path for f in files}
    assert "docs/policy-scope.md" not in paths


def test_empty_stage_docs_still_yield_agents_and_readme_stubs():
    project = _project()
    files = build_seed_files(project, {})
    by_path = {f.path: f.content for f in files}

    assert "AGENTS.md" in by_path
    assert "No constitution has been generated" in by_path["AGENTS.md"]
    assert "README.md" in by_path
    assert "No scope/spec has been generated" in by_path["README.md"]
    # No dedicated doc for stages with nothing to show.
    assert "docs/scope.md" not in by_path
    assert "docs/architecture.md" not in by_path
    assert "docs/tasks.md" not in by_path
    # Conventions always ships — as a stub pointing at AGENTS.md when there's
    # no constitution to scan.
    assert "docs/conventions.md" in by_path
    assert "AGENTS.md" in by_path["docs/conventions.md"]


def test_every_file_carries_a_provenance_footer():
    project = _project()
    files = build_seed_files(project, {"constitution": "Rules."})
    for f in files:
        assert project.id in f.content
        assert "Generated by PromptZone" in f.content


def test_missing_stages_do_not_crash():
    project = _project()
    # None values and a totally absent key must both be handled gracefully.
    stage_docs = {"constitution": None, "specify": "", "plan": None}
    files = build_seed_files(project, stage_docs)
    paths = {f.path for f in files}
    assert "AGENTS.md" in paths
    assert "README.md" in paths
    assert "docs/scope.md" not in paths
    assert "docs/architecture.md" not in paths
    assert "docs/tasks.md" not in paths


# --------------------------------------------------------------------------- #
# Deployment templates (ADR 0021)
# --------------------------------------------------------------------------- #
def test_no_template_builds_no_deployment_files():
    """Backward compatibility at the builder level: the deployment builder is
    separate from build_seed_files precisely so a project with no template
    cannot be affected by it at all."""
    project = Project(name="P", workspace_id="w", owner_id="u")
    assert build_deployment_files(project, None) == []


def test_template_builds_scaffold_workflow_and_docs():
    project = Project(
        name="Rocket",
        workspace_id="w",
        owner_id="u",
        deployment_config=DeploymentConfig(template_id="static-r2"),
    )
    files = build_deployment_files(project, "https://preview.test/p/")
    paths = {f.path for f in files}
    assert ".github/workflows/deploy.yml" in paths
    assert "site/index.html" in paths
    assert "docs/deployment.md" in paths

    doc = next(f.content for f in files if f.path == "docs/deployment.md")
    assert "https://preview.test/p/" in doc
    assert "Rocket" in doc


def test_withdrawn_template_seeds_nothing_rather_than_failing():
    """A selection that no longer resolves must not cost the project its repo
    and its AI context — those are still worth having."""
    project = Project(
        name="P",
        workspace_id="w",
        owner_id="u",
        deployment_config=DeploymentConfig(template_id="retired-template"),
    )
    assert build_deployment_files(project, None) == []


def test_deployment_files_do_not_collide_with_the_derived_documents():
    """The two builders are concatenated into one commit, so a shared path
    would mean one silently overwriting the other in the tree."""
    project = Project(
        name="P",
        workspace_id="w",
        owner_id="u",
        deployment_config=DeploymentConfig(template_id="static-r2"),
    )
    derived = {f.path for f in build_seed_files(project, {})}
    deployment = {f.path for f in build_deployment_files(project, None)}
    assert derived.isdisjoint(deployment)


def test_docker_compose_is_a_customer_owned_provider_template():
    template = get_template("docker-compose")
    assert template is not None
    assert template.provider_credential_kind == "ssh-docker"
    # Nobody mints the URL of a server the customer administers, so a human
    # names it and both sides read the same stored value.
    assert template.url_kind == "platform"
    assert template.platform_url_source == "project_value:public_url"
    assert template.provider in PROVIDERS


def test_docker_compose_seeds_a_dockerfile_a_compose_file_and_the_fixed_workflow():
    paths = {path for path, _, _ in template_files("docker-compose")}
    assert "Dockerfile" in paths
    assert "compose.yaml" in paths
    assert ".github/workflows/deploy.yml" in paths
    # The layout directories are an implementation detail of the composed
    # scaffold and must never reach a customer's repository.
    assert not any(p.startswith(("base/", "runtimes/", "services/")) for p in paths)


def test_docker_compose_opens_a_deployment_first_and_never_weakens_host_checking():
    workflow = next(
        content
        for path, content, _ in template_files("docker-compose")
        if path == ".github/workflows/deploy.yml"
    )
    # Opening the deployment before the build is what lets the Preview tab show
    # "building" immediately instead of nothing until the deploy finishes.
    assert workflow.index("Open deployment") < workflow.index("Build the image")
    assert "environment_url" in workflow
    # A pull request must never reach the deploy credential — and here that
    # credential is shell access to the customer's host.
    assert "pull_request_target" not in workflow
    # The key travels to whichever machine the admin's own host key names.
    assert "StrictHostKeyChecking yes" in workflow
    assert "StrictHostKeyChecking=no" not in workflow


def test_next_vercel_is_a_customer_owned_provider_template():
    template = get_template("next-vercel")
    assert template is not None
    assert template.provider_credential_kind == "vercel"
    # Vercel mints the hostname, so the URL arrives with the delivery rather
    # than being computed by the platform up front.
    assert template.url_kind == "provider"
    assert template.provider in PROVIDERS


def test_next_vercel_seeds_a_next_app_and_the_fixed_workflow_path():
    paths = {path for path, _, _ in template_files("next-vercel")}
    assert ".github/workflows/deploy.yml" in paths
    assert "next.config.mjs" in paths
    assert "app/page.tsx" in paths
    # Stored as `<name>.tmpl` so they never take effect inside this repository;
    # they must arrive in the customer's repo under their real names.
    assert {"package.json", "tsconfig.json", ".gitignore"} <= paths


def test_next_vercel_bakes_the_frame_ancestor_at_build_time():
    files = dict((path, content) for path, content, _ in template_files("next-vercel"))
    # The header is what makes `embeddable=True` earned rather than lucky: the
    # Preview tab frames this app because the app names it, not because Vercel
    # happens to send no framing header.
    assert "frame-ancestors" in files["next.config.mjs"]
    assert "PZ_WEB_ORIGIN" in files["next.config.mjs"]
    workflow = files[".github/workflows/deploy.yml"]
    # `vercel build` runs the Next.js build on the runner, so PZ_WEB_ORIGIN has
    # to be in THAT step's environment. Setting it only on the deploy step
    # would produce a preview that silently refuses to frame.
    build = workflow.index("vercel build")
    assert workflow.rindex("PZ_WEB_ORIGIN", 0, build) > workflow.index("Build")


def test_next_vercel_reports_its_own_url_and_opens_a_deployment_first():
    workflow = next(
        content
        for path, content, _ in template_files("next-vercel")
        if path == ".github/workflows/deploy.yml"
    )
    assert workflow.index("Open deployment") < workflow.index("vercel deploy")
    assert "environment_url" in workflow
    assert "pull_request_target" not in workflow
    # Production, not a Vercel preview deployment: Deployment Protection gates
    # preview deployments behind a Vercel login by default, and a login wall
    # cannot be reviewed by a stakeholder.
    assert "--prod" in workflow


def test_next_vercels_pull_request_check_cannot_reach_the_deploy_token():
    workflow = next(
        content
        for path, content, _ in template_files("next-vercel")
        if path == ".github/workflows/deploy.yml"
    )
    check = workflow.index("  check:")
    deploy = workflow.index("  deploy:")
    assert "secrets." not in workflow[check:deploy]
