"""app/integrations/repo_seed.py: pure, I/O-free derivation of the files
seeded into a project's repo at the tech_review -> repo_created transition.
"""

from __future__ import annotations

from app.integrations.repo_seed import build_seed_files
from app.models.schemas import Project


def _project(**overrides) -> Project:
    defaults = dict(name="Rocket", workspace_id="ws-1", owner_id="alice")
    defaults.update(overrides)
    return Project(**defaults)


def test_full_stage_docs_produce_all_files():
    project = _project()
    constitution = (
        "# Constitution\n\nSome rules.\n\n"
        "## Conventions\n\n- Use snake_case.\n- No TODOs.\n\n"
        "## Other\n\nMore stuff."
    )
    stage_docs = {
        "constitution": constitution,
        "specify": "# Scope\n\nBuild a rocket.",
        "plan": "# Architecture\n\nUse staged boosters.",
        "tasks": "# Tasks\n\nT001: build stage one.",
    }
    files = build_seed_files(project, stage_docs)
    paths = {f.path for f in files}
    assert paths == {
        "AGENTS.md",
        "README.md",
        "docs/scope.md",
        "docs/architecture.md",
        "docs/tasks.md",
        "docs/conventions.md",
    }

    by_path = {f.path: f.content for f in files}
    assert "Some rules." in by_path["AGENTS.md"]
    assert "Build a rocket." in by_path["README.md"]
    assert by_path["docs/scope.md"].startswith("# Scope")
    assert "Use staged boosters." in by_path["docs/architecture.md"]
    assert "T001" in by_path["docs/tasks.md"]
    assert "Use snake_case." in by_path["docs/conventions.md"]
    assert "Other" not in by_path["docs/conventions.md"]


def test_empty_stage_docs_still_yield_agents_and_readme_stubs():
    project = _project()
    files = build_seed_files(project, {})
    by_path = {f.path: f.content for f in files}

    assert "AGENTS.md" in by_path
    assert "No constitution has been generated" in by_path["AGENTS.md"]
    assert "README.md" in by_path
    assert "No scope/spec has been generated" in by_path["README.md"]
    # No dedicated doc for stages with nothing to show.
    assert "docs/scope.md" not in by_path
    assert "docs/architecture.md" not in by_path
    assert "docs/tasks.md" not in by_path
    # Conventions always ships — as a stub pointing at AGENTS.md when there's
    # no constitution to scan.
    assert "docs/conventions.md" in by_path
    assert "AGENTS.md" in by_path["docs/conventions.md"]


def test_every_file_carries_a_provenance_footer():
    project = _project()
    files = build_seed_files(project, {"constitution": "Rules."})
    for f in files:
        assert project.id in f.content
        assert "Generated by PromptZone" in f.content


def test_missing_stages_do_not_crash():
    project = _project()
    # None values and a totally absent key must both be handled gracefully.
    stage_docs = {"constitution": None, "specify": "", "plan": None}
    files = build_seed_files(project, stage_docs)
    paths = {f.path for f in files}
    assert "AGENTS.md" in paths
    assert "README.md" in paths
    assert "docs/scope.md" not in paths
    assert "docs/architecture.md" not in paths
    assert "docs/tasks.md" not in paths
