"""GET .../repository/docs-status and POST .../repository/sync-docs.

After a project's repository exists, its stage documents stay editable and
the seeded copies in the repository drift. The status route compares the
rebuilt seed against the default branch's tree by git blob sha; the sync
route writes the changed views to a `pw/sync-docs-*` branch and opens (or
updates) one pull request. It never writes to the default branch.
"""

from __future__ import annotations

import asyncio
import logging
import re
from datetime import datetime, timedelta

import pytest
from fastapi.testclient import TestClient

from app.integrations.github import (
    FakeGithubClient,
    GithubCompareTooLargeError,
    GithubRefUpdateRejectedError,
    GithubWriteError,
)
from app.integrations.repo_seed import build_seed_files
from app.main import create_app
from app.models.schemas import Role
from tests._repo_docs_helpers import (
    ALICE,
    BOB,
    STAGE_DOCS,
    TOKEN,
    _connect,
    _created_project,
    _workspace,
    _write_stage,
)


@pytest.fixture
def client() -> TestClient:
    app = create_app()
    with TestClient(app) as c:
        c.app.state.github_client = FakeGithubClient()
        yield c


def _fake(client: TestClient) -> FakeGithubClient:
    return client.app.state.github_client


def _repo_name(client: TestClient) -> str:
    return _fake(client).commits[0]["repo"]


def _status(client: TestClient, pid: str, headers: dict = ALICE) -> dict:
    res = client.get(f"/projects/{pid}/repository/docs-status", headers=headers)
    assert res.status_code == 200, res.text
    return res.json()


def _states(body: dict) -> dict[str, str]:
    return {f["path"]: f["state"] for f in body["files"]}


def _sync(client: TestClient, pid: str, headers: dict = ALICE):
    return client.post(f"/projects/{pid}/repository/sync-docs", headers=headers)


def test_status_is_current_right_after_creation(client: TestClient):
    pid = _created_project(client)

    body = _status(client, pid)

    states = _states(body)
    assert states, body
    assert set(states.values()) == {"current"}
    assert {"AGENTS.md", "README.md", "docs/architecture.md"} <= set(states)
    assert body["open_sync_pr"] is None


_ISO_DATE = re.compile(r"\d{4}-\d{2}-\d{2}")


def test_status_stays_current_on_a_later_day(client: TestClient, monkeypatch):
    """The seed footer carries no date: a status read the day after creation
    must not report every document as changed."""
    pid = _created_project(client)
    fake = _fake(client)
    committed = fake.sha_files[fake.branch_heads[_repo_name(client)]]
    footers = [
        line
        for content in committed.values()
        for line in content.splitlines()
        if "Generated by PromptWorkspace for project" in line
    ]
    assert footers
    assert not any(_ISO_DATE.search(line) for line in footers), footers

    project = client.app.state.repository.get_project(pid)
    today = [(f.path, f.content) for f in build_seed_files(project, STAGE_DOCS)]

    class _Tomorrow(datetime):
        @classmethod
        def now(cls, tz=None):
            return datetime.now(tz) + timedelta(days=1)

    # Both import styles: `datetime.datetime.now()` and a module-level
    # `from datetime import datetime` (raising=False: the seed needs neither).
    monkeypatch.setattr("datetime.datetime", _Tomorrow)
    monkeypatch.setattr("app.integrations.repo_seed.datetime", _Tomorrow, raising=False)

    assert [(f.path, f.content) for f in build_seed_files(project, STAGE_DOCS)] == today
    states = _states(_status(client, pid))
    assert states and set(states.values()) == {"current"}


def test_editing_the_plan_marks_docs_architecture_out_of_date(client: TestClient):
    pid = _created_project(client)

    _write_stage(client, pid, "plan", "# Architecture\n\nNow with a queue worker.\n")

    states = _states(_status(client, pid))
    assert states["docs/architecture.md"] == "out_of_date"
    assert {p: s for p, s in states.items() if p != "docs/architecture.md"} == {
        p: "current" for p in states if p != "docs/architecture.md"
    }


def test_missing_documents_are_skipped_not_reported(client: TestClient):
    pid = _created_project(client, stages=("specify", "constitution", "tasks"))

    states = _states(_status(client, pid))

    assert "docs/architecture.md" not in states
    assert set(states.values()) == {"current"}


def test_hand_edited_file_is_reported_and_goes_in_the_pr(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    full_name = _repo_name(client)
    head = asyncio.run(fake.get_branch_head(TOKEN, full_name, "main"))
    fake.sha_files[head]["AGENTS.md"] = "hand edited"

    assert _states(_status(client, pid))["AGENTS.md"] == "out_of_date"

    res = _sync(client, pid)
    assert res.status_code == 200, res.text
    assert "AGENTS.md" in res.json()["files"]
    assert "AGENTS.md" in fake.commits[-1]["paths"]
    body = fake.pull_requests[0]["body"]
    assert "AGENTS.md" in body
    assert "edited by hand" in body


def test_sync_opens_one_pr_with_only_changed_docs(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    full_name = _repo_name(client)
    main_head = fake.branch_heads[full_name]
    _write_stage(client, pid, "plan", "# Architecture\n\nNow with a queue worker.\n")

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    out = res.json()
    assert "docs/architecture.md" in out["files"]
    assert "AGENTS.md" not in out["files"] and "docs/scope.md" not in out["files"]
    assert out["branch"].startswith("pw/sync-docs-")
    assert len(fake.pull_requests) == 1
    pr = fake.pull_requests[0]
    assert pr["state"] == "open" and pr["head"] == out["branch"] and pr["base"] == "main"
    assert out["pr_number"] == pr["number"] and out["pr_url"] == pr["html_url"]
    assert fake.commits[-1]["branch"] == out["branch"]
    assert fake.commits[-1]["paths"] == out["files"]
    assert fake.branch_heads[full_name] == main_head

    status = _status(client, pid)
    assert status["open_sync_pr"] == {
        "number": pr["number"],
        "url": pr["html_url"],
        "foreign_changes": False,
    }


def test_second_sync_updates_the_same_pull_request(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    _write_stage(client, pid, "plan", "# Architecture\n\nNow with a queue worker.\n")
    first = _sync(client, pid)
    assert first.status_code == 200, first.text
    first_body = fake.pull_requests[0]["body"]
    assert "docs/scope.md" not in first_body
    _write_stage(client, pid, "plan", "# Architecture\n\nQueue worker and a cache.\n")
    _write_stage(client, pid, "specify", "# Scope\n\nStory time for schools too.\n")

    second = _sync(client, pid)

    assert second.status_code == 200, second.text
    assert len(fake.pull_requests) == 1
    assert second.json()["pr_number"] == first.json()["pr_number"]
    assert second.json()["branch"] == first.json()["branch"]
    sync_commits = [c for c in fake.commits if c["branch"] == first.json()["branch"]]
    assert len(sync_commits) == 2
    full_name = _repo_name(client)
    assert f"update_pull_request:{full_name}:1" in fake.call_log
    assert "docs/scope.md" in second.json()["files"]
    updated_body = fake.pull_requests[0]["body"]
    assert "docs/scope.md" in updated_body
    assert updated_body != first_body
    branch_head = fake.branch_refs[(full_name, first.json()["branch"])]
    assert fake.sha_files[branch_head]["docs/architecture.md"].startswith(
        "# Architecture\n\nQueue worker and a cache."
    )


def test_synced_files_read_in_pull_request_and_a_second_click_is_409(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", "# Architecture\n\nNow with a queue worker.\n")
    assert _sync(client, pid).status_code == 200

    states = _states(_status(client, pid))
    assert states["docs/architecture.md"] == "in_pull_request"
    assert {s for p, s in states.items() if p != "docs/architecture.md"} == {"current"}

    again = _sync(client, pid)
    assert again.status_code == 409
    assert again.json()["detail"] == "repository_docs_current"
    assert len(_fake(client).pull_requests) == 1


def test_editing_another_doc_after_a_sync_commits_only_that_doc(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    _write_stage(client, pid, "plan", "# Architecture\n\nNow with a queue worker.\n")
    first = _sync(client, pid).json()
    _write_stage(client, pid, "specify", "# Scope\n\nStory time for schools too.\n")

    states = _states(_status(client, pid))
    assert states["docs/scope.md"] == "out_of_date"
    assert states["docs/architecture.md"] == "in_pull_request"

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    # README.md carries the Specify text too, so it changes with docs/scope.md;
    # docs/architecture.md is already on the branch and is not committed again.
    assert res.json()["files"] == ["README.md", "docs/scope.md"]
    assert res.json()["branch"] == first["branch"]
    assert fake.commits[-1]["branch"] == first["branch"]
    assert fake.commits[-1]["paths"] == ["README.md", "docs/scope.md"]
    body = fake.pull_requests[0]["body"]
    assert "docs/scope.md" in body and "docs/architecture.md" in body
    assert set(_states(_status(client, pid)).values()) == {"current", "in_pull_request"}


def test_an_unreadable_sync_branch_falls_back_to_the_default_branch(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    _write_stage(client, pid, "plan", "# Architecture\n\nNow with a queue worker.\n")
    branch = _sync(client, pid).json()["branch"]
    branch_head = fake.branch_refs[(_repo_name(client), branch)]
    real_entries = fake.get_tree_entries

    async def failing_on_the_branch(token, repo, sha, *, recursive=True):
        if sha == branch_head:
            raise GithubWriteError("fake branch read failure", status_code=500)
        return await real_entries(token, repo, sha, recursive=recursive)

    fake.get_tree_entries = failing_on_the_branch

    body = _status(client, pid)
    assert _states(body)["docs/architecture.md"] == "out_of_date"
    assert body["open_sync_pr"] is not None


def test_sync_when_nothing_changed_is_409(client: TestClient):
    pid = _created_project(client)

    res = _sync(client, pid)

    assert res.status_code == 409
    assert res.json()["detail"] == "repository_docs_current"
    assert _fake(client).pull_requests == []


def test_deployment_files_are_never_in_the_pr(client: TestClient):
    pid = _created_project(client, template_id="static-r2")
    fake = _fake(client)
    full_name = _repo_name(client)
    head = fake.branch_heads[full_name]
    # The template's files really are in the repository, and docs/deployment.md
    # is built from the plan: a sync that took deployment files would move it.
    seeded = fake.commits[0]["paths"]
    assert {".github/workflows/deploy.yml", "site/index.html", "docs/deployment.md"} <= set(
        seeded
    )
    # Hand edits to template-owned files must not pull them into the sync.
    fake.sha_files[head][".github/workflows/deploy.yml"] = "on: push\n"
    fake.sha_files[head]["site/index.html"] = "<html></html>"
    fake.sha_files[head]["docs/deployment.md"] = "# Deploy\n"
    for stage, content in STAGE_DOCS.items():
        _write_stage(client, pid, stage, content + "\nRevised.\n")

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    committed = [p for c in fake.commits[1:] for p in c["paths"]]
    assert committed
    assert not any(p.startswith(".github/") or p.startswith("site/") for p in committed)
    assert "docs/deployment.md" not in committed
    paths = {f["path"] for f in _status(client, pid)["files"]}
    assert not any(p.startswith(".github/") or p.startswith("site/") for p in paths)


def test_token_without_pull_request_permission(client: TestClient, caplog):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", "# Architecture\n\nNow with a queue worker.\n")
    fake = _fake(client)
    fake.fail_pr_status = 403

    with caplog.at_level(logging.WARNING, logger="promptworkspace.repository_docs"):
        res = _sync(client, pid)

    assert res.status_code == 400
    assert res.json()["detail"] == "github_pr_permission_denied"
    # The branch and its commit stay behind (accepted); the warning names it so
    # an operator can find it.
    (orphan,) = [b for (_, b) in fake.branch_refs if b.startswith("pw/sync-docs-")]
    assert any(orphan in r.getMessage() for r in caplog.records)


def test_sync_is_admin_only_and_status_is_member_readable(client: TestClient):
    pid = _created_project(client)
    ws_id = client.get(f"/projects/{pid}", headers=ALICE).json()["workspace_id"]
    client.app.state.repository.add_member(ws_id, "bob", Role.member, invited_by="alice")
    _write_stage(client, pid, "plan", "# Architecture\n\nNow with a queue worker.\n")

    assert client.get(f"/projects/{pid}/repository/docs-status", headers=BOB).status_code == 200
    res = _sync(client, pid, headers=BOB)
    assert res.status_code == 403
    assert _fake(client).pull_requests == []


def test_not_created_and_imported_projects_are_refused(client: TestClient):
    ws_id = _workspace(client)
    _connect(client, ws_id)
    planning = client.post(
        "/projects", json={"name": "Draft", "workspace_id": ws_id}, headers=ALICE
    ).json()["id"]

    for res in (
        client.get(f"/projects/{planning}/repository/docs-status", headers=ALICE),
        _sync(client, planning),
    ):
        assert res.status_code == 409
        assert res.json()["detail"] == "repository_not_created"

    imported = client.post(
        "/projects", json={"name": "Brought", "workspace_id": ws_id}, headers=ALICE
    ).json()["id"]
    repository = client.app.state.repository
    repository.update_project_repo(
        imported, "https://github.com/acme/brought", 4242, "main", repo_origin="imported"
    )
    repository.update_project_lifecycle_status(imported, "repo_created")

    for res in (
        client.get(f"/projects/{imported}/repository/docs-status", headers=ALICE),
        _sync(client, imported),
    ):
        assert res.status_code == 409
        assert res.json()["detail"] == "sync_not_supported_for_imported_repository"


def test_legacy_imported_project_without_an_origin_is_refused(client: TestClient):
    """A project imported before `repo_origin` existed reaches `repo_created`
    with no recorded origin. Nothing tells it apart from a legacy scratch
    project, so it reads as imported (the migration's NULL-as-imported rule)."""
    ws_id = _workspace(client)
    _connect(client, ws_id)
    legacy = client.post(
        "/projects", json={"name": "Old import", "workspace_id": ws_id}, headers=ALICE
    ).json()["id"]
    repository = client.app.state.repository
    repository.update_project_repo(legacy, "https://github.com/acme/old-import", 4343, "main")
    repository.update_project_lifecycle_status(legacy, "repo_created")
    assert repository.get_project(legacy).repo_origin is None

    for res in (
        client.get(f"/projects/{legacy}/repository/docs-status", headers=ALICE),
        _sync(client, legacy),
    ):
        assert res.status_code == 409
        assert res.json()["detail"] == "sync_not_supported_for_imported_repository"


V2_PLAN = "# Architecture\n\nNow with a queue worker.\n"


def test_a_plan_edited_back_after_a_sync_is_reverted_in_the_pull_request(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    first = _sync(client, pid).json()

    # Back to the content the default branch already has.
    _write_stage(client, pid, "plan", STAGE_DOCS["plan"])
    assert _states(_status(client, pid))["docs/architecture.md"] == "out_of_date"

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    assert res.json()["files"] == ["docs/architecture.md"]
    assert res.json()["branch"] == first["branch"]
    assert fake.commits[-1]["branch"] == first["branch"]
    body = fake.pull_requests[0]["body"]
    assert "Changed back to the default branch" in body
    assert "docs/architecture.md" in body
    assert len(fake.pull_requests) == 1
    states = _states(_status(client, pid))
    assert states["docs/architecture.md"] == "current"
    assert _sync(client, pid).json()["detail"] == "repository_docs_current"


def _race_branch(client: TestClient) -> tuple[FakeGithubClient, str, str]:
    """The branch name a sync from the current default-branch head picks."""
    fake = _fake(client)
    full_name = _repo_name(client)
    head = fake.branch_heads[full_name]
    return fake, full_name, f"pw/sync-docs-{head[:12]}"


def test_sync_branch_is_named_after_the_default_branch_head(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    _, _, expected = _race_branch(client)

    assert _sync(client, pid).json()["branch"] == expected


def test_a_sync_racing_another_ends_with_one_pull_request(client: TestClient):
    """Two syncs from the same head: the second finds no PR, then loses the
    branch name to the first, re-reads, and adds to the first one's PR."""
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake, full_name, branch = _race_branch(client)
    head = fake.branch_heads[full_name]
    asyncio.run(fake.create_branch(TOKEN, full_name, branch, head))
    asyncio.run(fake.create_pull_request(TOKEN, full_name, branch, "main", "t", "b"))
    real_find = fake.find_open_pull_request
    calls = []

    async def first_misses(token, repo, prefix, base, author=None):
        calls.append(prefix)
        if len(calls) == 1:
            return None
        return await real_find(token, repo, prefix, base, author=author)

    fake.find_open_pull_request = first_misses

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    assert len(calls) == 2
    assert len(fake.pull_requests) == 1
    assert res.json()["pr_number"] == 1 and res.json()["branch"] == branch
    assert fake.commits[-1]["branch"] == branch
    assert fake.branch_heads[full_name] == head


def test_a_branch_left_by_a_closed_pull_request_is_adopted(client: TestClient):
    """A sync PR closed without merging leaves its branch (with its commit)
    while the default branch has not moved: the next sync commits onto that
    same branch and opens one new PR from it."""
    pid = _created_project(client)
    fake, full_name, branch = _race_branch(client)
    head = fake.branch_heads[full_name]
    _write_stage(client, pid, "plan", V2_PLAN)
    assert _sync(client, pid).json()["branch"] == branch
    fake.pull_requests[0]["state"] = "closed"
    _write_stage(client, pid, "plan", "# Architecture\n\nQueue worker and a cache.\n")

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    assert res.json()["branch"] == branch
    assert res.json()["files"] == ["docs/architecture.md"]
    assert fake.commits[-1]["branch"] == branch
    open_prs = [p for p in fake.pull_requests if p["state"] == "open"]
    assert len(open_prs) == 1 and open_prs[0]["head"] == branch
    assert res.json()["pr_number"] == open_prs[0]["number"] == 2
    assert [b for (_, b) in fake.branch_refs] == [branch]
    assert fake.branch_heads[full_name] == head


def test_a_branch_another_sync_is_still_uploading_is_adopted(client: TestClient):
    """The other sync created the branch but has not opened its PR yet: this
    sync adopts the branch and opens the one PR."""
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake, full_name, branch = _race_branch(client)
    asyncio.run(fake.create_branch(TOKEN, full_name, branch, fake.branch_heads[full_name]))

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    assert res.json()["branch"] == branch
    assert len(fake.pull_requests) == 1 and fake.pull_requests[0]["head"] == branch
    assert [b for (_, b) in fake.branch_refs] == [branch]


def test_a_sync_whose_pull_request_was_opened_first_by_another_ends_with_one(
    client: TestClient,
):
    """Both syncs found no PR and share the branch; the other one opened the
    PR first, so this one's create answers "already exists" and it updates
    that PR instead."""
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake, full_name, branch = _race_branch(client)
    asyncio.run(fake.create_branch(TOKEN, full_name, branch, fake.branch_heads[full_name]))
    asyncio.run(fake.create_pull_request(TOKEN, full_name, branch, "main", "t", "first body"))
    real_find = fake.find_open_pull_request
    calls = []

    async def misses_twice(token, repo, prefix, base, author=None):
        calls.append(prefix)
        if len(calls) <= 2:
            return None
        return await real_find(token, repo, prefix, base, author=author)

    fake.find_open_pull_request = misses_twice

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    assert len(calls) == 3
    assert len(fake.pull_requests) == 1
    assert res.json()["pr_number"] == 1 and res.json()["branch"] == branch
    assert fake.pull_requests[0]["body"] != "first body"
    assert "docs/architecture.md" in fake.pull_requests[0]["body"]


def test_a_fixed_token_retries_onto_the_same_branch(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake, _, branch = _race_branch(client)
    fake.fail_pr_status = 403
    assert _sync(client, pid).json()["detail"] == "github_pr_permission_denied"
    fake.fail_pr_status = None
    commits = len(fake.commits)

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    assert res.json()["branch"] == branch
    # The branch already holds the change from the failed attempt.
    assert len(fake.commits) == commits
    assert len(fake.pull_requests) == 1 and fake.pull_requests[0]["head"] == branch
    assert [b for (_, b) in fake.branch_refs] == [branch]


def test_a_failing_second_pull_request_lookup_maps_like_the_first(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake, full_name, branch = _race_branch(client)
    asyncio.run(fake.create_branch(TOKEN, full_name, branch, fake.branch_heads[full_name]))
    calls = []

    async def fails_second(token, repo, prefix, base, author=None):
        calls.append(prefix)
        if len(calls) == 1:
            return None
        raise GithubWriteError("fake pulls 403", status_code=403)

    fake.find_open_pull_request = fails_second

    res = _sync(client, pid)

    assert res.status_code == 400
    assert res.json()["detail"] == "github_pr_permission_denied"


def test_a_pull_request_branch_that_moved_is_not_written_over(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    branch = _sync(client, pid).json()["branch"]
    _write_stage(client, pid, "specify", "# Scope\n\nStory time for schools too.\n")
    full_name = _repo_name(client)
    commits = len(fake.commits)
    real_commit = fake.create_commit_with_files

    async def someone_pushed_first(token, repo, branch_name, files, message, **kw):
        fake.branch_refs[(repo, branch_name)] = "someone-elses-commit"
        return await real_commit(token, repo, branch_name, files, message, **kw)

    fake.create_commit_with_files = someone_pushed_first

    res = _sync(client, pid)

    assert res.status_code == 409
    assert res.json()["detail"] == "github_branch_conflict"
    assert len(fake.commits) == commits
    assert fake.branch_refs[(full_name, branch)] == "someone-elses-commit"


def test_a_commit_the_token_cannot_write_is_write_forbidden(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake = _fake(client)
    fake.fail_on_commit = True
    fake.write_failure_status = 403

    res = _sync(client, pid)

    assert res.status_code == 400
    assert res.json()["detail"] == "github_write_forbidden"


def test_a_branch_the_token_cannot_create_is_write_forbidden(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake = _fake(client)

    async def not_found(token, repo, branch, from_sha):
        raise GithubWriteError("fake create_branch 404", status_code=404)

    fake.create_branch = not_found

    res = _sync(client, pid)

    assert res.status_code == 400
    assert res.json()["detail"] == "github_write_forbidden"
    assert fake.pull_requests == []


def test_a_rule_on_the_sync_branch_is_branch_protected(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake = _fake(client)

    async def rejected(*args, **kwargs):
        raise GithubRefUpdateRejectedError("fake ruleset", status_code=422)

    fake.create_commit_with_files = rejected

    res = _sync(client, pid)

    assert res.status_code == 409
    assert res.json()["detail"] == "github_branch_protected"


def test_a_repository_the_token_cannot_see_is_read_forbidden(client: TestClient):
    pid = _created_project(client)
    _fake(client).get_tree_failure_status = 404

    res = client.get(f"/projects/{pid}/repository/docs-status", headers=ALICE)

    assert res.status_code == 400
    assert res.json()["detail"] == "github_read_forbidden"


# A collaborator can push any branch named pw/sync-docs-*. The sync commits
# and opens or rewrites pull requests under the admin's token, so it must
# never adopt a branch that carries anything but planning documents, nor a
# pull request someone else opened.


def test_an_adopted_branch_with_a_foreign_file_is_refused(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake, full_name, branch = _race_branch(client)
    asyncio.run(fake.create_branch(TOKEN, full_name, branch, fake.branch_heads[full_name]))
    fake.branch_extra_files[(full_name, branch)] = [".github/workflows/deploy.yml"]
    commits = len(fake.commits)

    res = _sync(client, pid)

    assert res.status_code == 409
    assert res.json()["detail"] == "sync_branch_has_foreign_changes"
    assert len(fake.commits) == commits
    assert fake.pull_requests == []


def test_an_open_pull_request_branch_with_a_foreign_file_is_refused(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    branch = _sync(client, pid).json()["branch"]
    full_name = _repo_name(client)
    fake.branch_extra_files[(full_name, branch)] = [".github/workflows/deploy.yml"]
    _write_stage(client, pid, "specify", "# Scope\n\nStory time for schools too.\n")
    commits = len(fake.commits)
    body = fake.pull_requests[0]["body"]

    res = _sync(client, pid)

    assert res.status_code == 409
    assert res.json()["detail"] == "sync_branch_has_foreign_changes"
    assert len(fake.commits) == commits
    assert fake.pull_requests[0]["body"] == body
    status = _status(client, pid)
    assert status["open_sync_pr"]["foreign_changes"] is True


def test_a_branch_too_large_to_compare_is_refused(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    assert _sync(client, pid).status_code == 200
    _write_stage(client, pid, "specify", "# Scope\n\nStory time for schools too.\n")
    commits = len(fake.commits)

    async def too_large(token, repo, base, head):
        raise GithubCompareTooLargeError("fake 300 files")

    fake.compare_files = too_large

    res = _sync(client, pid)

    assert res.status_code == 409
    assert res.json()["detail"] == "sync_branch_has_foreign_changes"
    assert len(fake.commits) == commits
    assert _status(client, pid)["open_sync_pr"]["foreign_changes"] is True


def test_a_failing_comparison_does_not_break_the_status(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    assert _sync(client, pid).status_code == 200

    async def failing(token, repo, base, head):
        raise GithubWriteError("fake compare 500", status_code=500)

    fake.compare_files = failing

    status = _status(client, pid)
    assert status["open_sync_pr"]["foreign_changes"] is False
    assert _states(status)["docs/architecture.md"] == "in_pull_request"


def test_a_pull_request_by_another_login_is_not_reused(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake, full_name, ours = _race_branch(client)
    theirs = "pw/sync-docs-mallory"
    asyncio.run(fake.create_branch(TOKEN, full_name, theirs, fake.branch_heads[full_name]))
    asyncio.run(fake.create_pull_request(TOKEN, full_name, theirs, "main", "t", "their body"))
    fake.pull_requests[0]["author"] = "mallory"

    assert _status(client, pid)["open_sync_pr"] is None
    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    assert res.json()["branch"] == ours
    assert res.json()["pr_number"] == 2
    assert fake.pull_requests[0]["body"] == "their body"
    assert not any(c["branch"] == theirs for c in fake.commits)
    assert f"update_pull_request:{full_name}:1" not in fake.call_log


def test_a_pull_request_by_another_login_on_our_branch_name_is_refused(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake, full_name, branch = _race_branch(client)
    asyncio.run(fake.create_branch(TOKEN, full_name, branch, fake.branch_heads[full_name]))
    asyncio.run(fake.create_pull_request(TOKEN, full_name, branch, "main", "t", "their body"))
    fake.pull_requests[0]["author"] = "mallory"
    commits = len(fake.commits)

    status = _status(client, pid)
    res = _sync(client, pid)

    assert status["open_sync_pr"]["foreign_changes"] is True
    assert res.status_code == 409
    assert res.json()["detail"] == "sync_branch_has_foreign_changes"
    assert len(fake.commits) == commits
    assert fake.pull_requests[0]["body"] == "their body"


@pytest.mark.parametrize("call", ["find", "create", "update"])
def test_a_401_from_any_pull_request_call_is_permission_denied(client: TestClient, call):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake = _fake(client)
    if call == "update":
        assert _sync(client, pid).status_code == 200
        _write_stage(client, pid, "specify", "# Scope\n\nStory time for schools too.\n")

    async def unauthorized(*args, **kwargs):
        raise GithubWriteError("fake 401", status_code=401)

    target = {
        "find": "find_open_pull_request",
        "create": "create_pull_request",
        "update": "update_pull_request",
    }[call]
    setattr(fake, target, unauthorized)

    res = _sync(client, pid)

    assert res.status_code == 400
    assert res.json()["detail"] == "github_pr_permission_denied"


def test_a_branch_a_rule_refuses_to_create_is_branch_protected(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake = _fake(client)

    async def rule_violation(token, repo, branch, from_sha):
        raise GithubWriteError("fake create_branch 422 rule violations", status_code=422)

    fake.create_branch = rule_violation

    res = _sync(client, pid)

    assert res.status_code == 409
    assert res.json()["detail"] == "github_branch_protected"
    assert fake.pull_requests == []


def _adopt_with(client: TestClient, pid: str, *, extra=(), renames=()):
    """A leftover branch at the name the next sync takes, carrying `extra`
    paths and `renames` (previous, new) someone else pushed."""
    fake, full_name, branch = _race_branch(client)
    asyncio.run(fake.create_branch(TOKEN, full_name, branch, fake.branch_heads[full_name]))
    fake.branch_extra_files[(full_name, branch)] = list(extra)
    fake.branch_renames[(full_name, branch)] = list(renames)
    return fake, full_name, branch


def test_a_rename_from_a_foreign_path_is_refused(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake, _, _ = _adopt_with(
        client, pid, renames=[(".github/workflows/ci.yml", "docs/scope.md")]
    )
    commits = len(fake.commits)

    res = _sync(client, pid)

    assert res.status_code == 409
    assert res.json()["detail"] == "sync_branch_has_foreign_changes"
    assert len(fake.commits) == commits
    assert fake.pull_requests == []


def test_a_rename_from_a_foreign_path_shows_on_the_open_pull_request(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    branch = _sync(client, pid).json()["branch"]
    fake.branch_renames[(_repo_name(client), branch)] = [
        (".github/workflows/ci.yml", "docs/scope.md")
    ]

    assert _status(client, pid)["open_sync_pr"]["foreign_changes"] is True


def test_a_rename_between_two_document_views_is_allowed(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    _, _, branch = _adopt_with(client, pid, renames=[("docs/scope.md", "docs/architecture.md")])

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    assert res.json()["branch"] == branch


def test_a_planted_view_the_project_does_not_have_is_foreign(client: TestClient):
    """docs/policy-scope.md is a document path, but this project has no policy
    scope, so the sync never writes it: a branch carrying it is someone
    else's change."""
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    project = client.app.state.repository.get_project(pid)
    assert "docs/policy-scope.md" not in {
        f.path for f in build_seed_files(project, STAGE_DOCS)
    }
    fake, _, _ = _adopt_with(client, pid, extra=["docs/policy-scope.md"])
    commits = len(fake.commits)

    res = _sync(client, pid)

    assert res.status_code == 409
    assert res.json()["detail"] == "sync_branch_has_foreign_changes"
    assert len(fake.commits) == commits


def test_an_adopted_branch_holding_only_seeded_views_is_used(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake, full_name, branch = _adopt_with(client, pid, extra=["AGENTS.md", "docs/scope.md"])

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    assert res.json()["branch"] == branch
    assert fake.commits[-1]["branch"] == branch
    assert len(fake.pull_requests) == 1


def test_a_push_between_the_check_and_the_commit_is_a_conflict(client: TestClient):
    pid = _created_project(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    fake, full_name, branch = _adopt_with(client, pid)
    fake.push_after_compare[(full_name, branch)] = "someone-elses-commit"
    commits = len(fake.commits)

    res = _sync(client, pid)

    assert res.status_code == 409
    assert res.json()["detail"] == "github_branch_conflict"
    assert len(fake.commits) == commits
    assert fake.branch_refs[(full_name, branch)] == "someone-elses-commit"
    assert fake.pull_requests == []


def _forget_account_login(client: TestClient, pid: str) -> None:
    """A connection stored before the login was recorded."""
    repository = client.app.state.repository
    ws_id = repository.get_project(pid).workspace_id
    config = dict(repository.get_workspace(ws_id).integration_config)
    config["github"] = {k: v for k, v in config["github"].items() if k != "account_login"}
    repository.update_workspace(ws_id, integration_config=config)


def test_without_a_recorded_login_any_authors_pull_request_is_reused(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    first = _sync(client, pid).json()
    fake.pull_requests[0]["author"] = "mallory"
    _forget_account_login(client, pid)
    _write_stage(client, pid, "specify", "# Scope\n\nStory time for schools too.\n")

    res = _sync(client, pid)

    assert res.status_code == 200, res.text
    assert res.json()["pr_number"] == first["pr_number"]
    assert res.json()["branch"] == first["branch"]
    assert len(fake.pull_requests) == 1


def test_without_a_recorded_login_foreign_paths_are_still_refused(client: TestClient):
    pid = _created_project(client)
    fake = _fake(client)
    _write_stage(client, pid, "plan", V2_PLAN)
    branch = _sync(client, pid).json()["branch"]
    fake.pull_requests[0]["author"] = "mallory"
    fake.branch_extra_files[(_repo_name(client), branch)] = [".github/workflows/deploy.yml"]
    _forget_account_login(client, pid)
    _write_stage(client, pid, "specify", "# Scope\n\nStory time for schools too.\n")
    commits = len(fake.commits)

    res = _sync(client, pid)

    assert res.status_code == 409
    assert res.json()["detail"] == "sync_branch_has_foreign_changes"
    assert len(fake.commits) == commits
    assert _status(client, pid)["open_sync_pr"]["foreign_changes"] is True
